### ISSUE TITLE
add a tickbox to who attended the event and who didnt

### ISSUE THREAD

**Issue by hundred** [railsgirlslondon/railsgirls-london#214]
checkbox to store the details about who attended the event and who didnt 
there need to be an ability to also add a note per user attendance, so we can write the reason of not attending
this needs to be available for every student and coach per each event

**Comment by hundred** [comment]
@creature do you think you ll have time to do this before friday? if not ill pick it up tomorrow :)

I also would like to change the story slightly from just general attendance  to :
attendance friday
attendance saturday

**Comment by creature** [comment]
@hundred I was just about to send a PR for what I've done on this, though I'm not super-happy with it. You could either iterate on what I've done or start over from scratch, depending on whether you think it's the right kind of idea or not. (I don't think I'll have much more time to work on it before Friday, but I might be able to squeeze in a spare half an hour if there's some small tweaks you'd like).

**Comment by hundred** [comment]
yep that ll be the first iteration then, merged :) looks cool, thank you :)

**Comment by tonymarklove** [comment]
This looks done. Closing the issue. We can reopen or create a new issue for any improvements needed.
